### ISSUE TITLE
Lovely table of contents on your post pages

### ISSUE THREAD

**Issue by keegoid** [konklone/writing#21]
Eric,

I've really enjoyed reading your posts, especially the one about [writing in public](https://konklone.com/post/writing-in-public-syncing-with-github). I never thought about this concept until I read your post. Thanks for introducing Ben Balter. I'm learning a lot from you guys! I'm working on setting up my own blog for writing in public. I value this concept and hope people will be interested in contributing at some point.

*This issue should be labeled a request or question.*
I am always looking for ways to make websites, specifically reading of web content, more user friendly. What you've done with your toc at the top left of your posts is really nice. **Would you be willing to open source the code you used to create it?** If not, no worries. I can try to create it on my own.

Thanks for your time and for focusing on important issues that affect us "leaves". ;)

Kind Regards,
Keegan

**Comment by konklone** [comment]
Thank you very much for the kind words, Keegan!

So the code to do the TOC is open source, though it's integrated inside the larger repository for the blog itself: https://github.com/konklone/konklone.com

The bulk of the code is here: https://github.com/konklone/konklone.com/blob/master/public/js/post.js

And it depends on the HTML structure here: https://github.com/konklone/konklone.com/blob/master/app/views/post.erb

It also depends on the behavior of the Markdown renderer I'm using, which can take headers and automatically generate slugs from their text when rendering the body, and then can also separately generate a ToC with the same slugs: https://github.com/konklone/konklone.com/blob/master/app/helpers/rendering.rb#L131-L139

But yeah, I haven't pulled it out into a library or anything, mostly because it requires code at a few different places to make it all fit together.

You can see another modified, simpler example of the same thing at https://theunitedstates.io/licensing/

The code for that is here: https://github.com/unitedstates/licensing/blob/gh-pages/_layouts/default.html And it's pretty self-contained. It's simpler because the document is static and so the headers are all known and never change. This is different than a blog, where the headers are dynamic and can change at any time, and from post to post.

I hope this is helpful, and thanks again for the kind words!

**Comment by keegoid** [comment]
Wow, thanks so much Eric! I really appreciate your detailed response with examples. When I get it done, I'll send you an update so you can see it in action.

**Comment by konklone** [comment]
That'd be greatly appreciated!
